### ISSUE TITLE
I asked BBCan77 to use your list instead of The Great Wall DoH

### ISSUE THREAD

**Issue by travisboss** [oneoffdallas/dohservers#12]
Looks like The Great Wall DoH is no longer updated, I have asked BBCan77 if he can switch to your list as it seems to be maintined.  This would be for DNSBL and IP Blocking. 

Thanks for the list, I have compiled this list to adblock syntax.

**Comment by oneoffdallas** [comment]
Sounds good to me! Thanks for the heads up!
