### ISSUE TITLE
New resolvers to be added to the list

### ISSUE THREAD

**Issue by molink36** [oneoffdallas/dohservers#17]
The following DoH servers can be added to the list:

```
https://doh.post-factum.tk/dns-query
https://dns.njal.la/dns-query
https://doh.this.web.id/dns-query
https://dns.therifleman.name/dns-query
https://dns1.ryan-palmer.com/dns-query
https://doh.bortzmeyer.fr/
https://query.hdns.io/dns-query
https://opennic.i2pd.xyz/dns-query
```

Source:
[https://github.com/DNSCrypt/dnscrypt-resolvers](url)

**Comment by oneoffdallas** [comment]
Thanks for the adds @molink36! I've added all to the IPv4 list and the 3 with IPv6 were added to that respective list. In the future, please add directly to the respective lists for easier commits. Thanks!
