### ISSUE TITLE
mask.icloud.com and mask-h2.icloud.com

### ISSUE THREAD

**Issue by jpgpi250** [oneoffdallas/dohservers#20]
You have added mask.icloud.com and mask-h2.icloud.com to the list.
These domains should not be blocked, because the domains are used to allow network providers to control icloud private relay usage. According to [this](https://matduggan.com/how-does-apple-private-relay-work/) and [this](https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay) document, the DNS query reply needs to be NWDOMAIN. If the acces is simply blocked, there will be delays.

**Comment by travisboss** [comment]
For services like pi-hole and adguard home the default deny is `NXDOMAIN` in reading both articles (I have read the second one already), it might make more sense to block `mask.apple-dns.net` which is the initial hit to apple.

As far as what to do I will leave that to the maintainer, I just convert his list to adgurd syntax.

**Comment by jpgpi250** [comment]
you said: I just convert his list to adblock syntax.
can I ask where I can find the maintainers (original) list?

**Comment by travisboss** [comment]
This is the original list, I am downstream from this.

**Comment by oneoffdallas** [comment]
@travisboss @jpgpi250 Is the general consensus to leave both of them blocked?

**Comment by travisboss** [comment]
> @travisboss @jpgpi250 Is the general consensus to leave both of them blocked?

I think we both disagree here. haha.

**Comment by oneoffdallas** [comment]
IMO, the best approach is to leave them blocked based strictly on their purpose and then let others format and/or choose as you have done @travisboss. The only viable alternative would be to add mask.apple-dns.net instead, but that is the second query and it would be prone to issues if the alias ever changed. Thoughts?

**Comment by oneoffdallas** [comment]
I also feel like some of the nuance is based on the replying DNS server. Happy to hear additional feedback though.

**Comment by jpgpi250** [comment]
network administators are encouraged to ensure NXDOMAIN is returned by the DNS server, **this to ensure there is no delay**, and the user gets a warning. There are several ways to achieve this:
- pihole: latest version returns NXDOMAIN by default
- dnsmasq: _server=/mask.icloud.com/_ and _server=/mask-h2.icloud.com/_
- unbound: _local-zone: " mask.icloud.com." always_nxdomain_ and _local-zone: " mask-h2.icloud.com." always_nxdomain_.

If you want to block the relays (the result of the initial queries), you need to block (firewall IP block) the IPs for the domains _mask.apple-dns.net_ and _mask-t.apple-dns.net_, but this may change. 

You're assumption is correct, if apple changes the CNAME, the relays would no longer be blocked. Therefore, leave it as is, administrators need to use the correct approach to avoid delays, reply with NXDOMAIN.

**Comment by oneoffdallas** [comment]
Got it! Please let me know if any of these approaches need to change and I'm happy to reflect that here. I appreciate your input @travisboss and @jpgpi250!
