### ISSUE TITLE
various disconnect.me apps use their own DOH provider which is not included in this list

### ISSUE THREAD

**Issue by jpgpi250** [oneoffdallas/dohservers#27]
[Disconnect Privacy DNS App](https://apps.apple.com/app/apple-store/id1571342218) and [Disconnect Privacy Pro](https://itunes.apple.com/us/app/privacy-pro-protection-for/id1051960818) in the App Store.
domain: doh.disconnect.app

**Comment by oneoffdallas** [comment]
@jpgpi250 Added to both DNS lists. Thanks!
