### ISSUE TITLE
ControlD FreeDNS

### ISSUE THREAD

**Issue by stevenzhu25** [oneoffdallas/dohservers#30]
I was trying to add all ControlD Free DNS offerings to the list, however I've noticed they offered more variety than before. 
https://controld.com/free-dns?
Beside the regular ones, they have some No "xxx" (Ads / Adult / Dating / Gambling) etc and all can be freely combined. 
By stats, It potentially contain 511 (9+36+84+126+126+84+36+9+1) varieties of DoT hostnames (all under `*.freedns.controld.com`)...

I have no clue if all these should be listed under this, since it's DoH Servers (but there are DoT lists) or even how to add them all...

**Comment by oneoffdallas** [comment]
Added to IP lists

**Comment by stevenzhu25** [comment]
@oneoffdallas Thanks for the update! 
Should those DoH endpoints add to the hostname lists? 
On one hand I think it would offer full coverage of ControlD DoH/DoT endpoints, but on the other hand it's definitely wayyy too long...

**Comment by oneoffdallas** [comment]
Based on info from their site, all of the DoH use freedns.controld.com whereas DoT uses the highly customizable subdomains approach. freedns.controld.com and a few associated ones are already listed in the DoH lists. Granted, I'm basing all of that simply off of their site information so if you see anything different in practice, please let me know and/or add them to the lists. Thanks!
