### ISSUE TITLE
List of domains that are no longer in use

### ISSUE THREAD

**Issue by S8D** [oneoffdallas/dohservers#33]
I used the tool and checked the list of domains and found that some domains were no longer in use. Hope Dev also remove it from the list of domains please!
  Thank you!
Below is a list of domains that are no longer in use:

uncensored-dot.dnswarden.com
https://browserleaks.com/ip/uncensored-dot.dnswarden.com

jarjar.meganerd.nl
https://browserleaks.com/ip/jarjar.meganerd.nl

ecs-doh.dnswarden.com
https://browserleaks.com/ip/ecs-doh.dnswarden.com

dot.securedns.eu
https://browserleaks.com/ip/dot.securedns.eu

dot.au.ahadns.net
https://browserleaks.com/ip/dot.au.ahadns.net

doh.this.web.id
https://browserleaks.com/ip/doh.this.web.id

doh.securedns.eu
https://browserleaks.com/ip/doh.securedns.eu

doh.pi-dns.com
https://browserleaks.com/ip/doh.pi-dns.com

doh.netweaver.uk
https://browserleaks.com/ip/doh.netweaver.uk

doh.blockerdns.com
https://browserleaks.com/ip/doh.blockerdns.com

doh.au.ahadns.net
https://browserleaks.com/ip/doh.au.ahadns.net

dnses.alekberg.net
https://browserleaks.com/ip/dnses.alekberg.net

dns.nixnet.xyz
https://browserleaks.com/ip/dns.nixnet.xyz

dns.mrkaran.dev
https://browserleaks.com/ip/dns.mrkaran.dev

dns.larsdebruin.net
https://browserleaks.com/ip/dns.larsdebruin.net

dns.dns-over-https.com
https://browserleaks.com/ip/dns.dns-over-https.com

dns.cfiec.net
https://browserleaks.com/ip/dns.cfiec.net

dns.bitgeek.in
https://browserleaks.com/ip/dns.bitgeek.in

dns.arapurayil.com
https://browserleaks.com/ip/dns.arapurayil.com

adult-filter-dot.dnswarden.com
https://browserleaks.com/ip/adult-filter-dot.dnswarden.com

ads-doh.securedns.eu
https://browserleaks.com/ip/ads-doh.securedns.eu

adblock-dot.dnswarden.com
https://browserleaks.com/ip/adblock-dot.dnswarden.com

2.dnscrypt-cert.dns.seby.io
https://browserleaks.com/ip/2.dnscrypt-cert.dns.seby.io

**Comment by oneoffdallas** [comment]
Updated. Thanks for the assist @S8D!
