### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by myxal** [oneoffdallas/dohservers#5]
Hi, I need a v6-enabled version of these lists. I'll be making one shortly, and wanted to ask what implementation is preferable for you to pull back into your repository.

I currently only use the list.txt file, and my use case doesn't care if the complete list is in 1 or multiple files, so I don't have strong preference for any of the possible implementations:

- separate list-v6.txt with v6 addresses, hosts in the same order as in list.txt
- append the v6 list to list.txt at the end of the file
- for every line with v4 mapping in list.txt, insert a line with v6 mapping immediately after it

The same question and implementation options apply to iplist.txt, as I see it.

Cheers

**Comment by oneoffdallas** [comment]
Hey myxal! That's great! For the various implementations I can think of a 2nd file makes more sense. I created a new IPv6 list file for this purpose. Thanks again!
