### ISSUE TITLE
Identified as DNS but CDN

### ISSUE THREAD

**Issue by joedacris** [oneoffdallas/dohservers#8]
Unfortunately both IPs below in use for CDN for Cloudflare.  Blocking HTTPS to these IPs will break anything hosted by these IP addresses(hosted js files for wordpress theme).  Please update.

cdnjs.cloudflare.com

# dns.cloudflare.com
104.17.64.4
104.17.65.4

**Comment by caliban2** [comment]
It's both, CDN and DNS.
https://dns.cloudflare.com/dns-query has the same IPs.

I dunno, make it optional and drop a note in IP-list? So far I'm not seeing any ill effects by blocking them, but that may change.

**Comment by oneoffdallas** [comment]
Now listed as optional. Thanks @caliban2!
